# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: FastAPI - Basic Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  fastapi-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        
    - name: Instalar Poetry
      run: |
        pip install poetry
        
    - name: Instalar Dependências
      run: |
        poetry install --no-root --no-interaction

    - name: Rodar Testes 
      run: | 
        poetry run pytest
